### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/votenet#82]
Dear people from VoteNet,

We are currently integrating VoteNet within https://github.com/nicolas-chaulet/torch-points3d.

Would it be possible to have a contact point if we encounter trouble reproducing results ?

Here is the current PR: https://github.com/nicolas-chaulet/torch-points3d/pull/242

The model will look like this.

``` 
models:
    VoteNetPaper:
        class: votenet.VoteNetModel
        conv_type: "DENSE"
        define_constants:
            in_feat: 64
            num_layers_down: 4
            num_layers_up: 2
            num_proposal: 256
            num_features: 256
        backbone:
            model_type: "PointNet2"
            down_conv:
                module_name: PointNetMSGDown
                npoint: [2048, 1024, 512, 256]
                radii: [[0.2], [0.4], [0.8], [1.2]]
                nsamples: [[64], [32], [16], [16]]
                down_conv_nn: [[[FEAT + 3, in_feat, in_feat, in_feat * 2]], 
                               [[in_feat * 2 + 3, in_feat * 2, in_feat * 2, in_feat * 4]], 
                               [[in_feat * 4 + 3, in_feat * 2, in_feat * 2, in_feat * 4]], 
                               [[in_feat * 4 + 3, in_feat * 2, in_feat * 2, in_feat * 4]]]
                save_sampling_id: [False, True, False, False]
            up_conv:
                module_name: DenseFPModule
                up_conv_nn:
                    [
                        [in_feat * 4 + in_feat * 4, in_feat * 4, in_feat * 4],
                        [in_feat * 4 + in_feat * 4, in_feat * 4, num_features]
                    ]
                skip: True
        voting:
            module_name: VotingModule
            vote_factor: 1
            feat_dim: num_features
        proposal:
            module_name: ProposalModule
            vote_aggregation:
                module_name: PointNetMSGDown
                npoint: [num_proposal]
                radii: [0.3]
                nsample: [16]
                down_conv_nn: [[num_features, in_feat * 2, in_feat * 2, in_feat * 2]]
            num_class: ${data.num_classes}
            num_heading_bin: 1
            num_size_cluster: ${data.num_classes}
            mean_size_arr: 3
            num_proposal: num_proposal
            sampling: "seed_fps"
```
